import {expect,test,type Page} from '@playwright/test';

const clean=async(page:Page)=>{await page.addInitScript(()=>{localStorage.clear();localStorage.setItem('gas-onboarding-complete','1')});};
const addGenerator=async(page:Page,name:string)=>{await page.getByRole('button',{name:'Add Layer',exact:true}).first().click();await expect(page.locator('.generator-library')).toBeVisible();await page.getByRole('searchbox',{name:'Search generators'}).fill(name);await page.locator('.generator-choice').filter({hasText:name}).click();};

test('first creation: add, edit, randomize, save and export',async({page})=>{await clean(page);await page.goto('/');await addGenerator(page,'Flow Field');await expect(page.locator('.layer-card')).toHaveCount(2);const slider=page.locator('input[data-param]').first();await slider.evaluate((element:HTMLInputElement)=>{element.value=String(Number(element.min||0)+Number(element.step||1));element.dispatchEvent(new Event('input',{bubbles:true}))});await page.keyboard.press('ControlOrMeta+k');await page.locator('.command-palette input').fill('Randomize Layer');await page.getByRole('button',{name:/Randomize Layer/}).click();await page.locator('.artwork-name').fill('My Study');await page.keyboard.press('ControlOrMeta+s');await expect(page.getByText('Artwork saved',{exact:true})).toBeVisible();await page.keyboard.press('ControlOrMeta+e');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export full composition'}).click();expect((await download).suggestedFilename()).toContain('My-Study');});

test('composition: reorder, opacity, blend, solo, undo and redo',async({page})=>{await clean(page);await page.goto('/');await addGenerator(page,'Flow Field');await addGenerator(page,'Mandelbrot');await expect(page.locator('.layer-card')).toHaveCount(3);const active=page.locator('.layer-card.selected');await active.locator('[data-layer-opacity]').evaluate((element:HTMLInputElement)=>{element.value='.42';element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))});await active.locator('[data-layer-blend]').selectOption('screen');await active.getByRole('button',{name:/Solo/}).click();await active.locator('summary').click();await active.getByRole('button',{name:'Move down'}).click();await page.getByRole('button',{name:/Undo/}).click();await page.getByRole('button',{name:/Redo/}).click();expect(await page.locator('[data-layer-blend]').evaluateAll(elements=>elements.map(element=>(element as HTMLSelectElement).value))).toContain('screen');});

test('generator library supports search, categories and favorites',async({page})=>{await clean(page);await page.goto('/');await page.getByRole('button',{name:'Add Layer',exact:true}).first().click();await page.getByRole('searchbox',{name:'Search generators'}).fill('Mandelbrot');await expect(page.locator('.generator-card')).toHaveCount(1);await page.getByRole('button',{name:'Favorite Mandelbrot'}).click();await page.locator('.generator-choice').click();await expect(page.locator('.layer-card.selected')).toContainText('Mandelbrot');});

test('keyboard shortcuts open commands, undo, redo, duplicate, save and focus',async({page})=>{await clean(page);await page.goto('/');await addGenerator(page,'Waves');await page.keyboard.press('ControlOrMeta+z');await expect(page.locator('.layer-card')).toHaveCount(1);await page.keyboard.press('ControlOrMeta+Shift+z');await expect(page.locator('.layer-card')).toHaveCount(2);await page.keyboard.press('ControlOrMeta+d');await expect(page.locator('.layer-card')).toHaveCount(3);await page.keyboard.press('ControlOrMeta+k');await expect(page.locator('.command-palette')).toBeVisible();await page.locator('.command-palette input').fill('Fullscreen');await expect(page.getByRole('button',{name:/Toggle Fullscreen/})).toBeVisible();await page.keyboard.press('Escape');await page.keyboard.press('f');await expect(page.locator('.studio')).toHaveClass(/focus-mode/);await page.keyboard.press('f');await page.keyboard.press('ControlOrMeta+s');await expect(page.getByText('Artwork saved',{exact:true})).toBeVisible();});

test('mobile editor keeps canvas primary and panels touch friendly',async({page},testInfo)=>{await clean(page);await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('.studio')).toHaveAttribute('data-layout','mobile-portrait');await page.locator('.mobile-nav').getByRole('button',{name:'Layers'}).click();await expect(page.locator('.left-panel')).toBeVisible();await page.locator('.mobile-nav').getByRole('button',{name:'Parameters'}).click();await expect(page.locator('.right-panel')).toBeVisible();await page.locator('.mobile-nav').getByRole('button',{name:'Colors'}).click();await expect(page.locator('.colors-view')).toBeVisible();for(const button of await page.locator('.mobile-nav button').all())expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath('mobile-editor.png'),fullPage:true});});

test('tablet portrait uses contextual drawers and desktop remains canvas-led',async({page},testInfo)=>{await clean(page);await page.setViewportSize({width:820,height:1180});await page.goto('/');await expect(page.locator('.studio')).toHaveAttribute('data-layout','tablet-portrait');await page.locator('.mobile-nav').getByRole('button',{name:'Layers'}).click();await expect(page.locator('.left-panel')).toBeVisible();await page.locator('.mobile-nav').getByRole('button',{name:'Parameters'}).click();await expect(page.locator('.right-panel')).toBeVisible();await page.setViewportSize({width:1440,height:900});await expect(page.locator('.stage')).toBeVisible();const stage=await page.locator('.stage').boundingBox(),left=await page.locator('.left-panel').boundingBox(),right=await page.locator('.right-panel').boundingBox();expect(stage!.width).toBeGreaterThan(left!.width+right!.width);await page.locator('[data-zoom="in"]').click();await page.locator('[data-zoom="pan"]').click();const canvas=page.locator('#art-canvas'),box=(await canvas.boundingBox())!;await canvas.dispatchEvent('pointerdown',{pointerId:1,clientX:box.x+20,clientY:box.y+20});await canvas.dispatchEvent('pointermove',{pointerId:1,clientX:box.x+50,clientY:box.y+40});await canvas.dispatchEvent('pointerup',{pointerId:1,clientX:box.x+50,clientY:box.y+40});await expect(canvas).toHaveCSS('cursor','grab');expect(await canvas.getAttribute('style')).toContain('translate(30px, 20px)');await page.screenshot({path:testInfo.outputPath('desktop-editor.png'),fullPage:true});});

test('onboarding appears once and leads directly to the library',async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();await expect(page.getByRole('heading',{name:'Generative Art Studio'})).toBeVisible();await page.getByRole('button',{name:'Start creating'}).click();await expect(page.locator('.generator-library')).toBeVisible();await page.reload();await expect(page.locator('.onboarding-dialog')).toBeHidden();});

test('dark and light themes preserve readable editor controls',async({page},testInfo)=>{await clean(page);await page.emulateMedia({colorScheme:'dark'});await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await expect(page.locator('.artwork-name')).toBeVisible();await page.screenshot({path:testInfo.outputPath('dark-editor.png'),fullPage:true});await page.locator('[data-action-id="theme"]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(page.locator('.layer-card.selected')).toBeVisible();await page.screenshot({path:testInfo.outputPath('light-editor.png'),fullPage:true});});
