import {expect,test,type Page} from '@playwright/test';
const clean=async(page:Page)=>page.addInitScript(()=>{if(!sessionStorage.getItem('effects-cleaned')){localStorage.clear();sessionStorage.setItem('effects-cleaned','1')}localStorage.setItem('gas-onboarding-complete','1')});
const openEffects=async(page:Page)=>{await page.getByRole('button',{name:'Effects',exact:true}).click()};
const addEffect=async(page:Page,name:string)=>{await page.getByRole('button',{name:'Add Effect'}).click();await page.locator('.effect-library-item').filter({hasText:name}).click()};

test('blur can be edited, disabled and restored with undo redo',async({page})=>{await clean(page);await page.goto('/');await openEffects(page);await addEffect(page,'Blur');const card=page.locator('.effect-card').filter({hasText:'Blur'});await expect(card).toBeVisible();await card.locator('[data-effect-param="radius"]').evaluate((element:HTMLInputElement)=>{element.value='21';element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))});await card.getByRole('button',{name:'Disable Blur'}).click();await expect(card).toHaveClass(/disabled/);await card.getByRole('button',{name:'Enable Blur'}).click();await page.getByRole('button',{name:/Undo/}).click();await expect(card).toHaveClass(/disabled/);await page.getByRole('button',{name:/Redo/}).click();await expect(page.locator('.effect-card').filter({hasText:'Blur'})).not.toHaveClass(/disabled/)});

test('effect stack supports multiple effects and accessible ordering',async({page},testInfo)=>{await clean(page);await page.goto('/');await openEffects(page);await addEffect(page,'Bloom / Glow');await addEffect(page,'Brightness / Contrast');const brightness=page.locator('.effect-card').filter({hasText:'Brightness / Contrast'});await brightness.getByRole('button',{name:/Move Brightness.*up/}).click();await expect(page.locator('.effect-card').first()).toContainText('Brightness / Contrast');await expect(page.locator('.effect-card')).toHaveCount(2);await page.screenshot({path:testInfo.outputPath('particles-effects-stack.png'),fullPage:true})});

test('linear mask supports parameters, invert and temporary preview',async({page},testInfo)=>{await clean(page);await page.goto('/');await page.getByRole('button',{name:'Mask',exact:true}).click();await page.locator('[data-mask-type]').selectOption('linear-gradient');await page.locator('[data-mask-param="angle"]').evaluate((element:HTMLInputElement)=>{element.value='45';element.dispatchEvent(new Event('input',{bubbles:true}))});await page.getByRole('button',{name:'Invert'}).click();await expect(page.getByRole('button',{name:'Invert'})).toHaveClass(/active/);await page.getByRole('button',{name:'Show Mask'}).click();await expect(page.getByRole('button',{name:'Show Artwork'})).toBeVisible();await page.screenshot({path:testInfo.outputPath('linear-mask-preview.png'),fullPage:true});await page.getByRole('button',{name:'Show Artwork'}).click();await expect(page.getByRole('button',{name:'Show Mask'})).toBeVisible()});

test('saved artwork restores effects and masks after reload',async({page})=>{await clean(page);await page.goto('/');await openEffects(page);await addEffect(page,'Saturation');await page.getByRole('button',{name:'Mask',exact:true}).click();await page.locator('[data-mask-type]').selectOption('radial-gradient');await page.locator('.artwork-name').fill('Effects Study');await page.keyboard.press('ControlOrMeta+s');await page.reload();await page.getByRole('button',{name:'Effects',exact:true}).click();await expect(page.locator('.effect-card')).toContainText('Saturation');await page.getByRole('button',{name:'Mask',exact:true}).click();await expect(page.locator('[data-mask-type]')).toHaveValue('radial-gradient')});

test('mobile bottom sheet exposes effects and masks',async({page},testInfo)=>{await clean(page);await page.setViewportSize({width:390,height:844});await page.goto('/');await page.locator('.mobile-nav').getByRole('button',{name:'Parameters'}).click();await page.getByRole('button',{name:'Effects',exact:true}).click();await addEffect(page,'Hue Rotation');await expect(page.locator('.effect-card')).toBeVisible();await page.getByRole('button',{name:'Mask',exact:true}).click();await page.locator('[data-mask-type]').selectOption('noise');await expect(page.locator('[data-mask-param="seed"]')).toBeVisible();await page.screenshot({path:testInfo.outputPath('mobile-effects-mask.png'),fullPage:true})});
