import type {AnyGenerator,Palette,ParamValues,PreviewQuality} from '../types';
import type {GeneratorRegistry} from './generator-registry';
import type {EffectInstance} from './effect';
import type {MaskInstance,MaskType} from './mask';
import {MASK_DEFAULTS} from './mask';
import {defaultParameters,sanitizeParameters,sanitizeParameterValues} from './parameters';
import {effectRegistry} from './effects';

export const ARTWORK_VERSION=2 as const;
export type BlendMode='normal'|'multiply'|'screen'|'overlay'|'darken'|'lighten'|'color-dodge'|'color-burn'|'hard-light'|'soft-light'|'difference'|'exclusion';
export interface Layer{id:string;name:string;generatorId:string;seed:number;parameters:ParamValues;palette:Palette;visible:boolean;opacity:number;blendMode:BlendMode;locked:boolean;order:number;effects:EffectInstance[];mask:MaskInstance|null;}
export interface Artwork{id:string;name:string;version:typeof ARTWORK_VERSION;canvas:{transparentExport:boolean};background:{mode:'auto'|'custom';color:string};layers:Layer[];global:{adaptiveQuality:boolean;previewQuality:PreviewQuality};}
export const createId=()=>globalThis.crypto?.randomUUID?.()??`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function createArtwork(name='Untitled Artwork',idFactory:()=>string=createId):Artwork{return{id:idFactory(),name,version:ARTWORK_VERSION,canvas:{transparentExport:false},background:{mode:'auto',color:'#09080d'},layers:[],global:{adaptiveQuality:true,previewQuality:'auto'}}}
export function createLayer(generator:AnyGenerator,seed:number,palette:Palette,idFactory:()=>string=createId,order=0):Layer{return{id:idFactory(),name:generator.name,generatorId:generator.id,seed,parameters:defaultParameters(generator),palette:{...palette},visible:true,opacity:1,blendMode:'normal',locked:false,order,effects:[],mask:null}}
export function createMask(type:MaskType,idFactory:()=>string=createId):MaskInstance{return{id:idFactory(),type,enabled:true,strength:1,invert:false,parameters:{...MASK_DEFAULTS[type]}}}
export function normalizeArtwork(input:Artwork,registry:GeneratorRegistry):Artwork{const art:Artwork={...input,version:ARTWORK_VERSION,canvas:{transparentExport:Boolean(input.canvas?.transparentExport)},background:{mode:input.background?.mode==='custom'?'custom':'auto',color:input.background?.color||'#09080d'},global:{adaptiveQuality:input.global?.adaptiveQuality!==false,previewQuality:input.global?.previewQuality||'auto'},layers:[]};art.layers=(Array.isArray(input.layers)?input.layers:[]).flatMap(layer=>{const generator=registry.get(layer.generatorId);if(!generator)return[];const effects=(Array.isArray(layer.effects)?layer.effects:[]).flatMap((effect,order)=>{const definition=effect&&effectRegistry.get(effect.effectId);return definition?[{...effect,id:effect.id||createId(),enabled:effect.enabled!==false,parameters:sanitizeParameterValues(definition.parameters,effect.parameters||{}),order}]:[]});const validMask=layer.mask&&['linear-gradient','radial-gradient','noise'].includes(layer.mask.type);const mask=validMask&&layer.mask?{...layer.mask,id:layer.mask.id||createId(),enabled:layer.mask.enabled!==false,strength:Math.max(0,Math.min(1,Number.isFinite(Number(layer.mask.strength))?Number(layer.mask.strength):1)),invert:Boolean(layer.mask.invert),parameters:{...MASK_DEFAULTS[layer.mask.type],...(layer.mask.parameters||{})}}:null;return[{...layer,id:layer.id||createId(),name:layer.name||generator.name,parameters:sanitizeParameters(generator,layer.parameters||{}),palette:{...layer.palette},seed:Number.isFinite(layer.seed)?layer.seed:1,visible:layer.visible!==false,opacity:Math.max(0,Math.min(1,Number(layer.opacity)||0)),blendMode:layer.blendMode||'normal',locked:Boolean(layer.locked),effects,mask}]}) .sort((a,b)=>a.order-b.order).map((layer,order)=>({...layer,order}));return art}
