import {mulberry32} from '../random';import type {EffectDefinition,EffectRenderContext} from './effect';import {EffectRegistry} from './effect';
const slider=(key:string,label:string,value:number,min:number,max:number,step:number,group='Settings')=>({key,label,type:'slider' as const,default:value,min,max,step,group});
function clear(context:EffectRenderContext){const{ctx}=context.target;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,context.width,context.height);ctx.restore()}
function filtered(filter:(p:Record<string,number>)=>string):EffectDefinition['apply']{return context=>{clear(context);const ctx=context.target.ctx;ctx.save();ctx.filter=filter(context.parameters as Record<string,number>);ctx.drawImage(context.source,0,0,context.width,context.height);ctx.restore()}}
const definitions:EffectDefinition[]=[
  {id:'blur',name:'Blur',description:'Softens detail with a Gaussian blur.',category:'Blur',performanceCost:'medium',parameters:[slider('radius','Radius',8,0,60,1)],apply:filtered(p=>`blur(${p.radius}px)`)},
  {id:'bloom',name:'Bloom / Glow',description:'Adds a luminous halo to bright forms.',category:'Stylize',performanceCost:'high',parameters:[slider('threshold','Threshold',.55,0,1,.01),slider('intensity','Intensity',.8,0,2,.05),slider('radius','Radius',14,1,50,1)],apply:context=>{clear(context);const p=context.parameters as Record<string,number>,ctx=context.target.ctx,scale=context.quality.mode==='export'?1:context.quality.resolutionScale;ctx.drawImage(context.source,0,0,context.width,context.height);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=p.intensity;ctx.filter=`brightness(${1+p.threshold}) contrast(${1+p.threshold}) blur(${p.radius*scale}px)`;ctx.drawImage(context.source,0,0,context.width,context.height);ctx.restore()}},
  {id:'brightness-contrast',name:'Brightness / Contrast',description:'Balances light and tonal separation.',category:'Color',performanceCost:'low',parameters:[slider('brightness','Brightness',1,0,2,.01),slider('contrast','Contrast',1,0,2,.01)],apply:filtered(p=>`brightness(${p.brightness}) contrast(${p.contrast})`)},
  {id:'saturation',name:'Saturation',description:'Controls color intensity.',category:'Color',performanceCost:'low',parameters:[slider('saturation','Saturation',1,0,3,.01)],apply:filtered(p=>`saturate(${p.saturation})`)},
  {id:'hue-rotation',name:'Hue Rotation',description:'Rotates every hue around the color wheel.',category:'Color',performanceCost:'low',parameters:[slider('angle','Angle',0,-180,180,1)],apply:filtered(p=>`hue-rotate(${p.angle}deg)`)},
  {id:'invert',name:'Invert',description:'Blends toward inverted colors.',category:'Color',performanceCost:'low',parameters:[slider('amount','Amount',1,0,1,.01)],apply:filtered(p=>`invert(${p.amount})`)},
  {id:'pixelate',name:'Pixelate',description:'Reduces the image into graphic blocks.',category:'Stylize',performanceCost:'medium',parameters:[slider('size','Pixel size',8,1,64,1)],apply:context=>{clear(context);const size=Number(context.parameters.size),w=Math.max(1,Math.ceil(context.width/size)),h=Math.max(1,Math.ceil(context.height/size)),ctx=context.target.ctx;ctx.imageSmoothingEnabled=false;ctx.drawImage(context.source,0,0,context.width,context.height,0,0,w,h);ctx.drawImage(context.target.canvas,0,0,w,h,0,0,context.width,context.height);ctx.imageSmoothingEnabled=true}},
  {id:'grain',name:'Noise / Grain',description:'Adds deterministic analog texture.',category:'Texture',performanceCost:'medium',parameters:[slider('amount','Amount',.18,0,1,.01),slider('size','Grain size',2,1,12,1),slider('seed','Seed',1,0,99999,1)],apply:context=>{clear(context);const ctx=context.target.ctx,p=context.parameters as Record<string,number>,random=mulberry32(p.seed),step=Math.max(1,Math.round(p.size/(context.quality.mode==='export'?1:context.quality.resolutionScale)));ctx.drawImage(context.source,0,0,context.width,context.height);ctx.save();ctx.globalCompositeOperation='overlay';for(let y=0;y<context.height;y+=step)for(let x=0;x<context.width;x+=step){const value=random()>.5?255:0;ctx.fillStyle=`rgba(${value},${value},${value},${p.amount*.35})`;ctx.fillRect(x,y,step,step)}ctx.restore()}},
  {id:'chromatic-aberration',name:'Chromatic Aberration',description:'Offsets color energy around edges.',category:'Stylize',performanceCost:'medium',parameters:[slider('amount','Amount',5,0,30,1),slider('angle','Direction',0,-180,180,1)],apply:context=>{clear(context);const p=context.parameters as Record<string,number>,angle=p.angle*Math.PI/180,x=Math.cos(angle)*p.amount,y=Math.sin(angle)*p.amount,ctx=context.target.ctx;ctx.drawImage(context.source,0,0,context.width,context.height);ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=.35;ctx.drawImage(context.source,x,y,context.width,context.height);ctx.drawImage(context.source,-x,-y,context.width,context.height);ctx.restore()}},
  {id:'wave-distortion',name:'Wave Distortion',description:'Displaces horizontal strips as a moving wave.',category:'Distortion',performanceCost:'high',parameters:[slider('strength','Strength',12,0,60,1),slider('frequency','Frequency',3,.2,12,.1),slider('speed','Speed',.4,0,3,.05)],apply:context=>{clear(context);const p=context.parameters as Record<string,number>,ctx=context.target.ctx,step=context.quality.mode==='export'?2:Math.max(2,Math.round(5/context.quality.resolutionScale));for(let y=0;y<context.height;y+=step){const offset=Math.sin(y/context.height*Math.PI*2*p.frequency+context.time*.001*p.speed)*p.strength;ctx.drawImage(context.source,0,y,context.width,step,offset,y,context.width,step)}}},
];
export const effectRegistry=new EffectRegistry();definitions.forEach(definition=>effectRegistry.register(definition));
